 <form class="well" action="<?php echo $this->url(array('action'=>'delete')); ?>" method="post">
     <p>
         Вы действительно хотите удалить отчет '<?php echo $this->escape($this->report['name']); ?>'?
     </p>
     <div>
         <input type="hidden" name="id" value="<?php echo $this->report['id']; ?>" />
         <input type="submit" name="confirm" value="Удалить" class="btn btn-danger"/>
         <input type="submit" name="confirm" value="Отменить" class="btn btn-warning"/>
     </div>
 </form>