<p>Вы действительно хотите удалить отчет
    '<?php echo $this->escape($this->report['name']); ?>'?
 </p>
 <form action="<?php echo $this->url(array('action'=>'delete')); ?>" method="post">
     <div>
         <input type="hidden" name="id" value="<?php echo $this->report['id']; ?>" />
         <input type="submit" name="confirm" value="Да" />
         <input type="submit" name="confirm" value="Нет" />
     </div>
 </form>