<p>Список отчётов</p>
<p>
    <?php if($this->acl['Report|Insert']){ ?>          
        <a href="<?php echo $this->url(array('controller'=>'report','action'=>'insert')) ?>">Добавить новый отчёт</a>
    <?php } ?>        
</p>
<table>
     <tr>
         <th>Название</th>
         <th>Операции</th>
     </tr>
     <?php foreach($this->reports as $report) { ?>
         <tr>
             <td>
                 <?php echo $this->escape($report->name) ?><br>
                 <a href="<?php echo $this->url(array('controller'=>'report-levels','action'=>'index','reportid'=>$report->id)) ?>">
                     Уровни
                 </a> 
                 <a href="<?php echo $this->url(array('controller'=>'report-items','action'=>'index','reportid'=>$report->id)) ?>">
                     Показатели
                 </a>
                 <a href="<?php echo $this->url(array('controller'=>'report-values','action'=>'index','reportid'=>$report->id)) ?>">
                     Значения показателей
                 </a>
             </td>
             <td>
                 <?php if ($this->acl['Report|Update']){ ?>
                    <a href="<?php echo $this->url(array('controller'=>'report','action'=>'update','id'=>$report->id)) ?>">
                        Изменить
                    </a> 
                 <?php } ?>        
                 <?php if ($this->acl['Report|Delete']){ ?>
                    <a href="<?php echo $this->url(array('controller'=>'report','action'=>'delete','id'=>$report->id)) ?>">
                        Удалить
                    </a> 
                 <?php } ?> 
             </td>
         </tr>
     <?php } ?>
 </table>