<p>Список уровней отчета</p>
<p>
    <a href="<?php echo $this->url(array('controller'=>'report-levels','action'=>'insert','reportid'=>$this->reportid)) ?>">Добавить новый уровень</a>
</p>
<table>
     <tr>
         <th>Название</th>
         <th>Номер</th>
         <th>Операции</th>
     </tr>
     <?php foreach($this->levels as $level) { ?>
         <tr>
             <td><?php echo $this->escape($level->name) ?></td>
             <td><?php echo $this->escape($level->number) ?></td>
             <td>
                 <a href="<?php echo $this->url(array('controller'=>'report-levels','action'=>'update','id'=>$level->id,'reportid'=>$this->reportid)) ?>">
                     Изменить
                 </a> 
                 <?php if($level->number == $this->lastnumber) { ?>
                 <a href="<?php echo $this->url(array('controller'=>'report-levels','action'=>'delete','id'=>$level->id,'reportid'=>$this->reportid)) ?>">
                     Удалить
                 </a> 
                 <?php } ?>
             </td>
         </tr>
     <?php } ?>
 </table>