<table>
    <tr>
        <?php if($this->acl['ReportValues|Confirm']){ ?>                                              
        <td valign="top">
            <p>Список пользователей</p>
            <table>
                <tr>
                    <th>ФИО</th>
                </tr>
                <?php foreach($this->users as $user) { ?>
                <tr>
                    <td>
                        <a href="<?php echo $this->url(array('controller'=>'report-values','action'=>'index','reportid'=>$this->report['id'],'userid'=>$user->id)) ?>">
                            <?php echo $this->escape($user->lastname).' '.$this->escape($user->firstname); ?>
                        </a>
                    </td>
                </tr>
                <?php } ?>
            </table>
        </td>
        <?php } ?> 
        <td>
<h3><?php echo $this->escape($this->report['name']) ?></h3>
<table class="table" style="width: 100%">
    <thead>
    <tr>
        <th>Номер</th>  
        <th>Название</th>    
        <th>Значение</th>
        <th>Статус</th>
    </tr>
    </thead>
     <?php foreach($this->items as $item) { ?>
         <tr id="<?php echo $this->escape($item->number) ?>">
             <td>
                 <?php echo $this->escape($item->number) ?>
             </td>
             <td><?php echo $this->escape($item->name) ?><br />
                 <?php if ($item->parentid == null) { ?>
                 <a><i class="icon-folder-open" onclick="collapse(this)"></i> Свернуть</a>
                 <?php } ?>
		 <?php if(($item->isvalue == 1) && ($this->values[$item->id] == 0) && ($this->userid == 0) && $this->acl['ReportValues|Insert']){ ?>
                     <a title="Добавить значение показателя отчёта" href="<?php echo $this->url(array('controller'=>'report-values','action'=>'insert','itemid'=>$item->id,'reportid'=>$this->report['id'])) ?>"><i class="icon-share-alt"></i> Добавить</a>
                 <?php } ?> 
                 <?php if(($item->isvalue == 1) && ($this->values[$item->id] != 0) && ($this->isconfirmed[$item->id] == 0) && ($this->userid == 0) && $this->acl['ReportValues|Delete']){ ?>
                     <a title="Удалить значение показателя отчёта" href="<?php echo $this->url(array('controller'=>'report-values','action'=>'delete','itemid'=>$item->id,'reportid'=>$this->report['id'])) ?>"><i class="icon-trash"></i> Удалить</a>
                 <?php } ?> 
                 <?php if(($item->isvalue == 1) && ($this->values[$item->id] != 0) && ($this->isconfirmed[$item->id] == 0) && ($this->userid == 0) && $this->acl['ReportValues|Update']){ ?>
                     <a title="Изменить значение показателя отчёта" href="<?php echo $this->url(array('controller'=>'report-values','action'=>'update','itemid'=>$item->id,'reportid'=>$this->report['id'])) ?>"><i class="icon-pencil"></i> Изменить</a>
                 <?php } ?>
             </td>      
             <td>
                 <?php if($this->values[$item->id])
                           echo $this->escape($this->values[$item->id]);
                 ?> 
             </td>
             <td>
                 <?php if(($item->isvalue == 1) && ($this->values[$item->id] != 0) && ($this->userid == 0)){
                           if ($this->isconfirmed[$item->id] == 1){?>
                               <i class="icon-ok"></i><?php
                           }
                           else {?>
                               <i class="icon-remove"></i><?php
                           }
                       }
                 ?>
                 <?php if(($item->isvalue == 1) && ($this->values[$item->id] != 0) && ($this->userid != 0)){ ?>
                     <input id="item_<?php echo $item->id; ?>" type="checkbox" onchange="confirmed(<?php echo $item->id; ?>,(this.checked)?1:0)" <?php if ($this->isconfirmed[$item->id] == 1) echo 'checked="checked"'; ?>/>
                 <?php } ?>
             </td>
         </tr>
     <?php } ?>
 </table>
<p>
    Итого: <?php echo $this->escape($this->summary); ?>, 
    <?php if($this->allconfirmed)
              echo "отчет подтвержден.";
          else
              echo "отчет не подтвержден.";
    ?>
</p>
        </td>
    </tr>
</table>
<script type="text/javascript">
    function collapse(cell){      
	if (cell.className == "icon-folder-close"){
	    cell.className="icon-folder-open";
            if (cell.parentNode.childNodes[1].textContent)
                cell.parentNode.childNodes[1].textContent=" Свернуть";        
            else
                cell.parentNode.childNodes[1].nodeValue=" Свернуть";
        }
        else{
            cell.className="icon-folder-close";
            if (cell.parentNode.childNodes[1].textContent)
                cell.parentNode.childNodes[1].textContent=" Развернуть";
            else
                cell.parentNode.childNodes[1].nodeValue=" Развернуть";
        }
        var q=cell.parentNode.parentNode.parentNode.id+".";
        q=q.replace(new RegExp("\\.",'g'),"\\.");
        $(document).ready(function() {
            var elem = $('tr[id^='+q+']');
	    for(var i=0; i < elem.length; i++){
		if (cell.className == "icon-folder-open")
 		    $(elem[i]).show("slow");
                else
                    $(elem[i]).hide("slow");
	    }
        });
    }
</script>
<script type="text/javascript">
    function confirmed(itemid,isconfirmed){
        require(["dojo/_base/xhr"],function(xhr) {         
            // Выполнение ajax-запроса.
            xhr.get({
                // Серверная страница обработки ajax-запроса.
                url: "<?php echo $this->url(array('controller'=>'report-values','action'=>'confirm')) ?>/itemid/"+itemid+"/isconfirmed/"+isconfirmed,
                // Формат получаемых данных.
                handleAs:"json",
                // Обработка успешного выполнения ajax-запроса.
                load: function() {
                    
                },
                error: function() {
                    
		}
            });     
        });
    }
</script>