<p>Вы действительно хотите удалить показатель
    '<?php echo $this->escape($this->item['name']); ?>'?
 </p>
 <form action="<?php echo $this->url(array('action'=>'delete')); ?>" method="post">
     <div>
         <input type="hidden" name="id" value="<?php echo $this->item['id']; ?>" />
         <input type="hidden" name="reportid" value="<?php echo $this->reportid; ?>" />
         <input type="submit" name="confirm" value="Да" />
         <input type="submit" name="confirm" value="Нет" />
     </div>
 </form>