<p>Список показателей отчета</p>
<table class="table table-bordered" style="width: 100%">
    <thead>
     <tr>
         <th>Номер</th>
         <th>Название</th>        
         <th>Значение</th>
         <th>Балл</th>
     </tr>
     </thead>
     <tr>
         <td>...</td>
         <td><a title="Добавить подчиненный показатель в отчёт" href="<?php echo $this->url(array('controller'=>'report-items','action'=>'insert','reportid'=>$this->reportid)) ?>"><i class="icon-share-alt"></i> Добавить</a></td>
         <td>...</td>
         <td>...</td>
     </tr>
     <?php foreach($this->items as $item) { ?>
         <tr>
             <td><?php echo $this->escape($item->number) ?></td>
             <td><?php echo $this->escape($item->name) ?><br />
                 <?php if($item->levelid != $this->lastlevelid) { ?>
                     <a title="Добавить подчиненный показатель в отчёт" href="<?php echo $this->url(array('controller'=>'report-items','action'=>'insert','parentid'=>$item->id,'levelid'=>$item->levelid,'reportid'=>$this->reportid)) ?>"><i class="icon-share-alt"></i> Добавить</a>
                 <?php } ?>
                 <a title="Изменить показатель отчёта" href="<?php echo $this->url(array('controller'=>'report-items','action'=>'update','id'=>$item->id,'reportid'=>$this->reportid)) ?>"><i class="icon-pencil"></i> Изменить</a>          
                 <?php if(!$this->hasChildren[$item->id]) { ?>
                     <a title="Удалить показатель из отчёта" href="<?php echo $this->url(array('controller'=>'report-items','action'=>'delete','id'=>$item->id,'reportid'=>$this->reportid)) ?>"><i class="icon-trash"></i> Удалить</a>    
                 <?php } ?> 
             </td>             
             <td><?php if($item->isvalue == 1) echo 'да'; else echo 'нет'; ?></td>
             <td><?php echo $this->escape($item->score) ?></td>
         </tr>
     <?php } ?>
 </table>