<p>Вы действительно хотите удалить пользователя 
    '<?php echo $this->escape($this->user['login']); ?>'?
</p>
<form action="<?php echo $this->url(array('action'=>'delete')); ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo $this->user['id']; ?>" />
        <input type="submit" name="confirm" value="Да" />
        <input type="submit" name="confirm" value="Нет" />
    </div>
</form>