<?php
$this->title = "Список пользователей";
$this->headTitle($this->title);
?>
<p>
    <?php 
    try{ 
        if (Zend_Acl_Factory::getInstance()->isAllowed(Zend_Auth::getInstance()->getIdentity()->login,"user","insert")){ ?>          
            <a href="<?php echo $this->url(array('controller'=>'user','action'=>'insert')) ?>">Добавить нового пользователя</a>              
    <?php }  
    }
    catch(Exception $e){
    }
    ?> 
</p>
<table>
    <tr>
        <th>Логин</th>
        <th>Имя</th>
        <th>Отчество</th>
        <th>Фамилия</th>
        <th>Функции</th>
    </tr>
    <?php foreach($this->users as $user) { ?>
    <tr>
    <td><?php echo $this->escape($user->login);?></td>
    <td><?php echo $this->escape($user->firstname);?></td>
    <td><?php echo $this->escape($user->middlename);?></td>
    <td><?php echo $this->escape($user->lastname);?></td>
    <td>
        <a href="<?php echo $this->url(array('controller'=>'user', 'action'=>'update', 'id'=>$user->id));?>">Изменить</a>
        <a href="<?php echo $this->url(array('controller'=>'user', 'action'=>'delete', 'id'=>$user->id));?>">Удалить</a>
    </td>
</tr>
<?php } ?>
</table>